### ISSUE TITLE
Fehler im Text

### ISSUE THREAD

**Issue by Ronoon** [bumaas/BlindControl#1]
Hallo bumaas,

In der Beschreibung der Sonnenstandsregelung hat sich der Gedankenteufel eingeschlichen :-)

Es heißt dort:
Dies erfolgt in zwei Stufen: Wenn die Temperatur 27°C übersteigt, wird der Rollladen um weitere 15% heruntergefahren, wenn die Temperatur 30°C übersteigt, dann wird der Rollladen auf eine Höhe von 10% heruntergefahren)

Und es sollte heißen:
Dies erfolgt in zwei Stufen: Wenn die Temperatur 27°C übersteigt, wird der Rollladen um weitere 15% heruntergefahren, wenn die Temperatur 30°C übersteigt, dann wird der Rollladen auf eine Höhe von **90%** heruntergefahren**.**

**Comment by bumaas** [comment]
Danke für den Hinweis. Ist im nächsten Stand korrigiert.
